# Generated by Django 4.0.2 on 2022-02-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_choice_submission_question_choice_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default='Select a choice...', max_length=1000),
        ),
    ]
